/*******************************************************************************
 * Copyright (c) 2006 Eclipse.org
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package org.eclipse.gmf.internal.xpand.expression.parser;

public interface ExpressionKWLexersym {
    public final static int
      Char_DollarSign = 27,
      Char_a = 8,
      Char_b = 28,
      Char_c = 5,
      Char_d = 17,
      Char_e = 1,
      Char_f = 11,
      Char_g = 29,
      Char_h = 18,
      Char_i = 6,
      Char_j = 19,
      Char_k = 30,
      Char_l = 2,
      Char_m = 20,
      Char_n = 12,
      Char_o = 7,
      Char_p = 13,
      Char_q = 31,
      Char_r = 9,
      Char_s = 4,
      Char_t = 3,
      Char_u = 10,
      Char_v = 32,
      Char_w = 14,
      Char_x = 15,
      Char_y = 21,
      Char_z = 33,
      Char_A = 22,
      Char_B = 34,
      Char_C = 23,
      Char_D = 35,
      Char_E = 24,
      Char_F = 36,
      Char_G = 37,
      Char_H = 38,
      Char_I = 39,
      Char_J = 40,
      Char_K = 41,
      Char_L = 25,
      Char_M = 42,
      Char_N = 43,
      Char_O = 44,
      Char_P = 45,
      Char_Q = 46,
      Char_R = 47,
      Char_S = 16,
      Char_T = 48,
      Char_U = 49,
      Char_V = 50,
      Char_W = 51,
      Char_X = 52,
      Char_Y = 53,
      Char_Z = 54,
      Char_EOF = 26;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "e",
                 "l",
                 "t",
                 "s",
                 "c",
                 "i",
                 "o",
                 "a",
                 "r",
                 "u",
                 "f",
                 "n",
                 "p",
                 "w",
                 "x",
                 "S",
                 "d",
                 "h",
                 "j",
                 "m",
                 "y",
                 "A",
                 "C",
                 "E",
                 "L",
                 "EOF",
                 "DollarSign",
                 "b",
                 "g",
                 "k",
                 "q",
                 "v",
                 "z",
                 "B",
                 "D",
                 "F",
                 "G",
                 "H",
                 "I",
                 "J",
                 "K",
                 "M",
                 "N",
                 "O",
                 "P",
                 "Q",
                 "R",
                 "T",
                 "U",
                 "V",
                 "W",
                 "X",
                 "Y",
                 "Z"
             };

    public final static boolean isValidForParser = true;
}
