/*******************************************************************************
 * Copyright (c) 2006 Eclipse.org
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package org.eclipse.gmf.internal.xpand.parser;

public interface XpandParsersym {
    public final static int
      TK_IDENT = 1,
      TK_STRING = 8,
      TK_INT_CONST = 18,
      TK_REAL_CONST = 19,
      TK_let = 27,
      TK_switch = 24,
      TK_implies = 42,
      TK_new = 20,
      TK_false = 21,
      TK_true = 22,
      TK_null = 23,
      TK_default = 43,
      TK_case = 44,
      TK_Collection = 3,
      TK_List = 4,
      TK_Set = 5,
      TK_typeSelect = 9,
      TK_collect = 10,
      TK_select = 11,
      TK_reject = 12,
      TK_exists = 13,
      TK_notExists = 14,
      TK_forAll = 15,
      TK_QUESTION_MARK = 45,
      TK_DCOLON = 28,
      TK_COLON = 30,
      TK_LPAREN = 2,
      TK_RPAREN = 6,
      TK_LCURLY = 16,
      TK_RCURLY = 32,
      TK_LSQUARE = 46,
      TK_RSQUARE = 47,
      TK_ARROW = 48,
      TK_NOT = 7,
      TK_AND = 49,
      TK_OR = 50,
      TK_ASSIGN = 51,
      TK_EQ = 52,
      TK_NE = 53,
      TK_GE = 54,
      TK_LE = 55,
      TK_GT = 56,
      TK_LT = 57,
      TK_PLUS = 58,
      TK_MINUS = 17,
      TK_MULTI = 29,
      TK_DIV = 59,
      TK_DOT = 34,
      TK_COMMA = 33,
      TK_BAR = 60,
      TK_IMPORT = 61,
      TK_EXTENSION = 62,
      TK_AROUND = 35,
      TK_ENDAROUND = 31,
      TK_DEFINE = 36,
      TK_ENDDEFINE = 37,
      TK_ERROR = 63,
      TK_EXPAND = 64,
      TK_FOR = 25,
      TK_SEPARATOR = 65,
      TK_AS = 38,
      TK_ITERATOR = 66,
      TK_FOREACH = 39,
      TK_ENDFOREACH = 67,
      TK_FILE = 68,
      TK_ENDFILE = 69,
      TK_IF = 70,
      TK_ELSEIF = 71,
      TK_ELSE = 72,
      TK_ENDIF = 73,
      TK_LET = 74,
      TK_ENDLET = 75,
      TK_PROTECT = 76,
      TK_CSTART = 77,
      TK_CEND = 78,
      TK_ID = 79,
      TK_DISABLE = 80,
      TK_ENDPROTECT = 81,
      TK_LG = 82,
      TK_EOF_TOKEN = 40,
      TK_TEXT = 26,
      TK_COMMENT = 41,
      TK_ERROR_TOKEN = 83;

      public final static String orderedTerminalSymbols[] = {
                 "",
                 "IDENT",
                 "LPAREN",
                 "Collection",
                 "List",
                 "Set",
                 "RPAREN",
                 "NOT",
                 "STRING",
                 "typeSelect",
                 "collect",
                 "select",
                 "reject",
                 "exists",
                 "notExists",
                 "forAll",
                 "LCURLY",
                 "MINUS",
                 "INT_CONST",
                 "REAL_CONST",
                 "new",
                 "false",
                 "true",
                 "null",
                 "switch",
                 "FOR",
                 "TEXT",
                 "let",
                 "DCOLON",
                 "MULTI",
                 "COLON",
                 "ENDAROUND",
                 "RCURLY",
                 "COMMA",
                 "DOT",
                 "AROUND",
                 "DEFINE",
                 "ENDDEFINE",
                 "AS",
                 "FOREACH",
                 "EOF_TOKEN",
                 "COMMENT",
                 "implies",
                 "default",
                 "case",
                 "QUESTION_MARK",
                 "LSQUARE",
                 "RSQUARE",
                 "ARROW",
                 "AND",
                 "OR",
                 "ASSIGN",
                 "EQ",
                 "NE",
                 "GE",
                 "LE",
                 "GT",
                 "LT",
                 "PLUS",
                 "DIV",
                 "BAR",
                 "IMPORT",
                 "EXTENSION",
                 "ERROR",
                 "EXPAND",
                 "SEPARATOR",
                 "ITERATOR",
                 "ENDFOREACH",
                 "FILE",
                 "ENDFILE",
                 "IF",
                 "ELSEIF",
                 "ELSE",
                 "ENDIF",
                 "LET",
                 "ENDLET",
                 "PROTECT",
                 "CSTART",
                 "CEND",
                 "ID",
                 "DISABLE",
                 "ENDPROTECT",
                 "LG",
                 "ERROR_TOKEN"
             };

    public final static boolean isValidForParser = true;
}
