#!/bin/bash
p=$(dirname $0)
type=${1/*.}
case $type in
java) language=$p/result/norm/Java/simple.Txl ;;
v) language=$p/result/norm/Verilog/verilog2.Txl ;;
problem) language=$p/result/norm/ProblemFrames/problem.Txl ;;
xml) language=$p/result/norm/XML/xml-mct.Txl ;;
q7) language=$p/result/norm/Q7/q7.Txl ;;
argument) language=$p/result/norm/Argument/argument.Txl ;;
c) language=$p/result/norm/C/cid.Txl ;;
sp) language=$p/result/norm/NLP/nlp.Txl ;;
uncal) language=$p/Txl/Uncal/uncal2java.Txl ;;
cal) language=$p/result/norm/Cal/Cal.Txl ;;
uml) language=$p/result/norm/UML/uml.Txl ;;
argument) language=$p/result/norm/Argument/argument.Txl ;;
cs) language=$p/result/norm/CSharp/csharp.Txl ;;
#cs) language=Txl/CSharp/cs.txl ;;
*) language=$type.Txl ;;
esac
if [ "$#" == "1" ]; then
	txl -i $p/Txl $1 -q $language 2> /dev/null
elif [ "$#" == "2" ]; then
	txl -i $p/Txl $1 -q $language - -diff $2 >& t.t
	grep -v TXL091 t.t
	rm -f t.t
else
	echo usage: $0 program [ program_to_compare ]
fi
