<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
   xmlns:xmi="http://www.omg.org/XMI"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FamilyMModel"
   nsURI="http:///FamilyMModel.ecore" nsPrefix="FamilyMModel">
 <eClassifiers xsi:type="ecore:EClass" name="Family">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
ordered="false"
   lowerBound="1" eType="ecore:EDataType
http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EReference" name="member"
ordered="false"
   lowerBound="1" upperBound="-1" eType="#//Member" containment="true"/>
</eClassifiers>
 <eClassifiers xsi:type="ecore:EClass" name="Member">
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
ordered="false"
   lowerBound="1" eType="ecore:EDataType
http://www.eclipse.org/emf/2002/Ecore#//EString"/>
   <eStructuralFeatures xsi:type="ecore:EAttribute" name="relation"
ordered="false"
   lowerBound="1" eType="ecore:EDataType
http://www.eclipse.org/emf/2002/Ecore#//EString"/>
</eClassifiers>
</ecore:EPackage>
