
diff -w raminfr.r79.v raminfr.r84.v > raminfr.r84.v.diff
diff -w raminfr.r84.v raminfr.r106.v > raminfr.r106.v.diff
diff -w timescale.r27.v timescale.r29.v > timescale.r29.v.diff
diff -w timescale.r29.v timescale.r106.v > timescale.r106.v.diff
diff -w uart_debug_if.r79.v uart_debug_if.r84.v > uart_debug_if.r84.v.diff
diff -w uart_debug_if.r84.v uart_debug_if.r106.v > uart_debug_if.r106.v.diff
diff -w uart_debug_if.r49.v uart_debug_if.r55.v > uart_debug_if.r55.v.diff
diff -w uart_debug_if.r55.v uart_debug_if.r65.v > uart_debug_if.r65.v.diff
diff -w uart_debug_if.r65.v uart_debug_if.r79.v > uart_debug_if.r79.v.diff
diff -w uart_defines.r27.v uart_defines.r29.v > uart_defines.r29.v.diff
diff -w uart_receiver.r64.v uart_receiver.r66.v > uart_receiver.r66.v.diff
diff -w uart_receiver.r66.v uart_receiver.r67.v > uart_receiver.r67.v.diff
diff -w uart_receiver.r67.v uart_receiver.r69.v > uart_receiver.r69.v.diff
diff -w uart_receiver.r47.v uart_receiver.r48.v > uart_receiver.r48.v.diff
diff -w uart_receiver.r69.v uart_receiver.r79.v > uart_receiver.r79.v.diff
diff -w uart_receiver.r48.v uart_receiver.r50.v > uart_receiver.r50.v.diff
diff -w uart_receiver.r79.v uart_receiver.r84.v > uart_receiver.r84.v.diff
diff -w uart_receiver.r50.v uart_receiver.r51.v > uart_receiver.r51.v.diff
diff -w uart_receiver.r84.v uart_receiver.r100.v > uart_receiver.r100.v.diff
diff -w uart_receiver.r51.v uart_receiver.r57.v > uart_receiver.r57.v.diff
diff -w uart_receiver.r100.v uart_receiver.r103.v > uart_receiver.r103.v.diff
diff -w uart_receiver.r57.v uart_receiver.r61.v > uart_receiver.r61.v.diff
diff -w uart_receiver.r27.v uart_receiver.r29.v > uart_receiver.r29.v.diff
diff -w uart_receiver.r103.v uart_receiver.r106.v > uart_receiver.r106.v.diff
diff -w uart_receiver.r61.v uart_receiver.r63.v > uart_receiver.r63.v.diff
diff -w uart_receiver.r29.v uart_receiver.r33.v > uart_receiver.r33.v.diff
diff -w uart_receiver.r63.v uart_receiver.r64.v > uart_receiver.r64.v.diff
diff -w uart_regs.r63.v uart_regs.r64.v > uart_regs.r64.v.diff
diff -w uart_regs.r47.v uart_regs.r48.v > uart_regs.r48.v.diff
diff -w uart_regs.r64.v uart_regs.r66.v > uart_regs.r66.v.diff
diff -w uart_regs.r48.v uart_regs.r50.v > uart_regs.r50.v.diff
diff -w uart_regs.r66.v uart_regs.r68.v > uart_regs.r68.v.diff
diff -w uart_regs.r50.v uart_regs.r52.v > uart_regs.r52.v.diff
diff -w uart_regs.r68.v uart_regs.r79.v > uart_regs.r79.v.diff
diff -w uart_regs.r39.v uart_regs.r40.v > uart_regs.r40.v.diff
diff -w uart_regs.r52.v uart_regs.r54.v > uart_regs.r54.v.diff
diff -w uart_regs.r40.v uart_regs.r41.v > uart_regs.r41.v.diff
diff -w uart_regs.r79.v uart_regs.r84.v > uart_regs.r84.v.diff
diff -w uart_regs.r54.v uart_regs.r56.v > uart_regs.r56.v.diff
diff -w uart_regs.r41.v uart_regs.r42.v > uart_regs.r42.v.diff
diff -w uart_regs.r84.v uart_regs.r87.v > uart_regs.r87.v.diff
diff -w uart_regs.r56.v uart_regs.r58.v > uart_regs.r58.v.diff
diff -w uart_regs.r42.v uart_regs.r43.v > uart_regs.r43.v.diff
diff -w uart_regs.r87.v uart_regs.r99.v > uart_regs.r99.v.diff
diff -w uart_regs.r58.v uart_regs.r59.v > uart_regs.r59.v.diff
diff -w uart_regs.r43.v uart_regs.r44.v > uart_regs.r44.v.diff
diff -w uart_regs.r27.v uart_regs.r29.v > uart_regs.r29.v.diff
diff -w uart_regs.r99.v uart_regs.r105.v > uart_regs.r105.v.diff
diff -w uart_regs.r59.v uart_regs.r60.v > uart_regs.r60.v.diff
diff -w uart_regs.r44.v uart_regs.r45.v > uart_regs.r45.v.diff
diff -w uart_regs.r29.v uart_regs.r31.v > uart_regs.r31.v.diff
diff -w uart_regs.r105.v uart_regs.r106.v > uart_regs.r106.v.diff
diff -w uart_regs.r60.v uart_regs.r63.v > uart_regs.r63.v.diff
diff -w uart_regs.r45.v uart_regs.r47.v > uart_regs.r47.v.diff
diff -w uart_regs.r31.v uart_regs.r32.v > uart_regs.r32.v.diff
diff -w uart_rfifo.r88.v uart_rfifo.r106.v > uart_rfifo.r106.v.diff
diff -w uart_rfifo.r79.v uart_rfifo.r84.v > uart_rfifo.r84.v.diff
diff -w uart_rfifo.r84.v uart_rfifo.r87.v > uart_rfifo.r87.v.diff
diff -w uart_rfifo.r87.v uart_rfifo.r88.v > uart_rfifo.r88.v.diff
diff -w uart_sync_flops.r98.v uart_sync_flops.r106.v > uart_sync_flops.r106.v.diff
diff -w uart_tfifo.r79.v uart_tfifo.r84.v > uart_tfifo.r84.v.diff
diff -w uart_tfifo.r84.v uart_tfifo.r106.v > uart_tfifo.r106.v.diff
diff -w uart_top.r84.v uart_top.r106.v > uart_top.r106.v.diff
diff -w uart_top.r27.v uart_top.r29.v > uart_top.r29.v.diff
diff -w uart_transmitter.r74.v uart_transmitter.r79.v > uart_transmitter.r79.v.diff
diff -w uart_transmitter.r79.v uart_transmitter.r84.v > uart_transmitter.r84.v.diff
diff -w uart_transmitter.r84.v uart_transmitter.r106.v > uart_transmitter.r106.v.diff
diff -w uart_transmitter.r27.v uart_transmitter.r29.v > uart_transmitter.r29.v.diff
diff -w uart_wb.r84.v uart_wb.r101.v > uart_wb.r101.v.diff
diff -w uart_wb.r101.v uart_wb.r106.v > uart_wb.r106.v.diff
diff -w uart_wb.r27.v uart_wb.r29.v > uart_wb.r29.v.diff
