//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-hudson-3037-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.05.08 at 04:44:06 PM MSD 
//


package org.ofsm.impl.schema;

import javax.xml.bind.annotation.AccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transition element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="transition">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://ofsm.sourceforge.net}when-event"/>
 *           &lt;element ref="{http://ofsm.sourceforge.net}from-state"/>
 *           &lt;element ref="{http://ofsm.sourceforge.net}to-state"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */

@XmlType(name = "", propOrder = {
    "whenEvent",
    "fromState",
    "toState"
})
@XmlRootElement(name = "transition", namespace = "http://ofsm.sourceforge.net")
public class Transition {

    @XmlElement(name = "when-event", namespace = "http://ofsm.sourceforge.net")
    protected String whenEvent;
    @XmlElement(name = "from-state", namespace = "http://ofsm.sourceforge.net")
    protected String fromState;
    @XmlElement(name = "to-state", namespace = "http://ofsm.sourceforge.net")
    protected String toState;

    /**
     * Gets the value of the whenEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhenEvent() {
        return whenEvent;
    }

    /**
     * Sets the value of the whenEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhenEvent(String value) {
        this.whenEvent = value;
    }

    /**
     * Gets the value of the fromState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromState() {
        return fromState;
    }

    /**
     * Sets the value of the fromState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromState(String value) {
        this.fromState = value;
    }

    /**
     * Gets the value of the toState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToState() {
        return toState;
    }

    /**
     * Sets the value of the toState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToState(String value) {
        this.toState = value;
    }

}
