//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace org.ofsm.impl.schema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ofsm.sourceforge.net")]
    [System.Xml.Serialization.XmlRootAttribute("state", Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class StateType : NamedObject {
        
        private string classNameField;
        
        /// <remarks/>
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ofsm.sourceforge.net")]
    public partial class NamedObject {
        
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class states {
        
        private StateType[] stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("state")]
        public StateType[] state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class events {
        
        private EventType[] eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event")]
        public EventType[] @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ofsm.sourceforge.net")]
    [System.Xml.Serialization.XmlRootAttribute("event", Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class EventType : NamedObject {
        
        private string classNameField;
        
        /// <remarks/>
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class transitions {
        
        private transition[] transitionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transition")]
        public transition[] transition {
            get {
                return this.transitionField;
            }
            set {
                this.transitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class transition {
        
        private string wheneventField;
        
        private string fromstateField;
        
        private string tostateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("when-event")]
        public string whenevent {
            get {
                return this.wheneventField;
            }
            set {
                this.wheneventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("from-state")]
        public string fromstate {
            get {
                return this.fromstateField;
            }
            set {
                this.fromstateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("to-state")]
        public string tostate {
            get {
                return this.tostateField;
            }
            set {
                this.tostateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("finite-state-machine", Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class finitestatemachine {
        
        private definitions definitionsField;
        
        private string initialstateField;
        
        private transitions transitionsField;
        
        /// <remarks/>
        public definitions definitions {
            get {
                return this.definitionsField;
            }
            set {
                this.definitionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("initial-state")]
        public string initialstate {
            get {
                return this.initialstateField;
            }
            set {
                this.initialstateField = value;
            }
        }
        
        /// <remarks/>
        public transitions transitions {
            get {
                return this.transitionsField;
            }
            set {
                this.transitionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://ofsm.sourceforge.net", IsNullable=false)]
    public partial class definitions {
        
        private states statesField;
        
        private events eventsField;
        
        /// <remarks/>
        public states states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
        
        /// <remarks/>
        public events events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
    }
}
