#rm -f *.java
rm -f *.diff 
rm -f *.normal
rm -f *.normal_error
rm -f *.ldiff 
rm -f *.java5 
rm -f *.java5_error 
rm -f *.norm_diff
rm -f *.norm 
rm -f *.norm_error
rm -f *.clone
rm -f *.clone_error
