#!/bin/bash
p=$(dirname $0)
if [ "$1" == "-comment" ]; then
  cc=cc
  shift
else
  cc=c
fi
type=${1/*.}
case $type in
#java) language=Java/api_clone_java ;;
java) language=Java/java ;;
1) language=Java/java ;;
v) language=Verilog/verilog2 ;;
problem) language=ProblemFrames/problem ;;
xml) language=XML/xml-mct ;;
q7) language=Q7/q7 ;;
argument) language=Argument/argument ;;
c) language=C/cid ;;
sp) language=NLP/nlp ;;
j) language=Java/java ;;
*) language=$type ;;
esac
mct=$p/../bin.`uname -s -m | sed 's/ /_/'`/"$language"$cc
if [ "$#" == "1" ]; then
	$mct $opt -q $1
elif [ "$#" == "2" ]; then
	echo $mct $opt -q $1 -diff $2
	$mct $opt -q $1 -diff $2 >& t.t
	grep -v TXL091 t.t
	rm -f t.t
else
	echo usage: mct program [program_to_compare]
fi
