#!/bin/bash
p=$(dirname $0)
type=${1/*.}
case $type in
java) language=api_clone_java ;;
v) language=verilog2 ;;
default) language=$type ;;
esac
mct=$p/../bin.`uname -s -m | sed 's/ /_/'`/"$language"c
	# echo $mct
if [ "$#" == "1" ]; then
	$mct -q $1 2> /dev/null 
elif [ "$#" == "2" ]; then
	$mct -q -attr $1 -diff $2 
else
echo usage: mct program [program_to_compare]
fi
