#!/bin/bash
p=$(dirname $0)
type=${1/*.}
case $type in
java) language=api_clone_java ;;
v) language=verilog2 ;;
*) language=$type ;;
esac
mct=$p/../bin.`uname -s -m | sed 's/ /_/'`/"$language"c
if [ "$#" == "1" ]; then
	$mct -q $1
elif [ "$#" == "2" ]; then
	$mct -q $1 -diff $2 >& t.t
	grep -v TXL091 t.t
	rm -f t.t
else
	echo usage: mct program [program_to_compare]
fi
