#!/bin/bash
p=$(dirname $0)
if [ "$1" == "-comment" ]; then
  cc=cc
  shift
else
  cc=c
fi
type=${1/*.}
case $type in
java) language=mdsd ;;
v) language=verilog2 ;;
*) language=$type ;;
esac
mct=$p/../bin.`uname -s -m | sed 's/ /_/'`/"$language"$cc
if [ "$#" == "1" ]; then
	$mct -s 400 $opt -q $1
elif [ "$#" == "2" ]; then
	$mct -s 400 $opt -attr -q $1 -diff $2 >& t.t
	grep -v TXL091 t.t
	rm -f t.t
else
	echo usage: mct program [program_to_compare]
fi
