#!/bin/bash
p=$(dirname $0)
type=${1/*.}
case $type in
java) language=api_clone_java ;;
v) language=verilog2 ;;
*) language=$type ;;
esac
mct=$p/../bin.`uname -s -m | sed 's/ /_/'`/txldb
if [ "$#" == "1" ]; then
	$mct -q $1 2> /dev/null 
elif [ "$#" == "2" ]; then
	if [ ! -e Txl/$language.Txl ]; then
		make Txl/$language.Txl 
	fi
	$mct -q -attr $1 Txl/$language.Txl - -diff $2
else
	echo usage: mct program [program_to_compare]
fi
